# TrayRunner Configuration
# You can mix items and groups in any order.

items:
  - type: item
    label: "Open Terminal"
    cmd: "x-terminal-emulator"
    terminal: false
    confirm: false

  - type: item
    label: "Open File Manager"
    cmd: "xdg-open ."
    terminal: false
    confirm: false

  - type: separator

  - type: group
    label: "System"
    items:
      - type: item
        label: "Update & Upgrade"
        cmd: "bash -lc 'sudo apt update && sudo apt -y upgrade'"
        terminal: true
        confirm: true

      - type: item
        label: "Restart NetworkManager"
        cmd: "bash -lc 'sudo systemctl restart NetworkManager'"
        terminal: true
        confirm: true

      - type: item
        label: "Check Disk Usage"
        cmd: "df -h"
        terminal: true
        confirm: false

      - type: item
        label: "System Info"
        cmd: "uname -a && uptime"
        terminal: true
        confirm: false

  - type: separator

  - type: group
    label: "Development"
    items:
      - type: item
        label: "Open VS Code"
        cmd: "code"
        terminal: false
        confirm: false

      - type: item
        label: "Git Status"
        cmd: "git status"
        terminal: true
        confirm: false

      - type: item
        label: "Python Version"
        cmd: "python3 --version"
        terminal: true
        confirm: false

  - type: separator

  - type: item
    label: "Custom Script"
    cmd: "/home/tim/scripts/myscript.sh --flag"
    terminal: false
    confirm: false
    env:
      CUSTOM_VAR: "value"
